### ISSUE TITLE
Message Flag

### ISSUE THREAD

**Issue by AljoschaMeyer** [dominictarr/packet-stream-codec#2]
Is the following correct? Packet-stream supports a "message" type (i.e. send something but don't expect an answer). Muxrpc (and consequently ssb) does not use messages. And packet-stream-codec is the codec used by muxrpc, so it does not provide a flag for "message" either.

Since there's 4 unused bits in the header anyways, couldn't the codec support messages as well?

Somewhat related, I'm probably going to call the rust module corresponding to this "muxrpc-codec", which seems to be the more appropriate name to me.

**Comment by dominictarr** [comment]
muxrpc did originally have messages, and that is why it's in packet-stream, but we later decided to remove them and forgot to remove them from packet-stream, it seems!
There just wasn't that much need for messages, and streams could do that anyway.

**Comment by dominictarr** [comment]
one thing I think we'll want to add is a json-like binary encoding, maybe [flexbuffers](https://google.github.io/flatbuffers/flexbuffers.html)
